# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "seedbank" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c7534c4bd34bfad65bcf71489b6eccd0bc08980670c016924afb51be5bf5417

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=2
  run:
    - python >=3.6
    - numpy >=1.17

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - seedbank
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://seedbank.lenskit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Unified API for seeding random number generators.
  description: |
    seedbank is a unified API for seeding a wide range of random number generators
    with a single seed call, and managing more sophisticated seeding needs through
    its support for NumPy generators and derived seeds.
  doc_url: https://seedbank.lenskit.org
  dev_url: https://github.com/lenskit/seedbank

extra:
  recipe-maintainers:
    - mdekstrand
